# Workflow to perform code quality checks on each commit/PR to main
name: Code Quality
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - "main"
  push:
    branches:
      - "main"
  merge_group:
    types: [checks_requested]
  # allow manually triggering on branches
  workflow_dispatch:

permissions:
  contents: read

env:
  go_version: 1.25.5

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Run automated tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
          check-latest: true
          cache: true

      - name: Run tests
        run: >
          go tool gotest.tools/gotestsum
          --format=github-actions
          --format-hide-empty-pkg
          --rerun-fails=2
          --rerun-fails-run-root-test
          --rerun-fails-report tmp/test-results/gotestsum-flake-report.txt
          --packages ./...
          --junitfile /tmp/test-results/go-test-report.xml
          --junitfile-hide-empty-pkg
          --junitfile-testcase-classname=short

      - name: Upload gotestsum reports
        uses: actions/upload-artifact@v4
        with:
          name: gotestsum-report
          path: /tmp/test-results/**
          overwrite: true
          retention-days: 7
        if: ${{ !cancelled() }}

      - name: Produce Test Summary
        uses: test-summary/action@v2
        with:
          paths: /tmp/test-results/**/*-report.xml
        if: ${{ !cancelled() }}

  golangci-lint:
    name: Lint with golangci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
          check-latest: true
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  reuse:
    name: Check REUSE compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Run REUSE Compliance Check
        uses: fsfe/reuse-action@v6
